#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
  echo "🚫 Direct push to '$branch' is not allowed. Use pull requests."
  exit 1
fi
